# Generated by Django 5.0.6 on 2024-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_starter_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclaim',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
