services:
  app:
    command:
      - uvicorn
      - config.asgi:application
      - --host
      - 0.0.0.0
      - --port
      - "${APP_INTERNAL_PORT:-8000}"
      - --workers
      - "4"
      - --log-level
      - warning
