global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 告警配置（可根据需要调整）
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 规则配置
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 监控目标配置
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:8001"] 