# Generated by Django 6.0.1 on 2026-01-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docpage',
            name='category',
        ),
        migrations.DeleteModel(
            name='DocCategory',
        ),
        migrations.DeleteModel(
            name='DocPage',
        ),
    ]
