# Generated by Django 5.0.6 on 2025-04-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_actor_created_time_actor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='movie',
            index_together=set(),
        ),
    ]
