# Generated by Django 5.0.6 on 2025-04-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_movie_index_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'year'], name='demo_movie_title_50f2dc_idx'),
        ),
    ]
