# Generated by Django 5.0.6 on 2025-04-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_movie_demo_movie_title_50f2dc_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': '演员', 'verbose_name_plural': '演员'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['name'], 'verbose_name': '音乐', 'verbose_name_plural': '音乐'},
        ),
        migrations.AlterModelOptions(
            name='musicalbum',
            options={'ordering': ['name'], 'verbose_name': '音乐专辑', 'verbose_name_plural': '音乐专辑'},
        ),
    ]
