# Generated by Django 5.0.6 on 2025-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('story', models.TextField(verbose_name='我们的故事')),
                ('mission', models.TextField(verbose_name='我们的使命')),
                ('email', models.EmailField(max_length=100, verbose_name='联系邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(verbose_name='地址')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
                'db_table': 'djs_about',
            },
        ),
    ]
