# Generated by Django 3.2.12 on 2022-09-28 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='配置项名称')),
                ('value', models.CharField(max_length=5000, verbose_name='配置项的值')),
                ('display_name', models.TextField(default='', verbose_name='显示名称')),
            ],
            options={
                'verbose_name': '通用配置',
                'verbose_name_plural': '通用配置',
                'db_table': 'django_starter_config',
            },
        ),
    ]
