# Generated by Django 5.0.6 on 2024-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_starter_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='软删除标志'),
        ),
    ]
