# Generated by Django 6.0.1 on 2026-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_historicaluserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='职位/头衔'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='职位/头衔'),
        ),
    ]
